version: '3'

services:
  go-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
    networks:
      - go-network
      
  go-pgadmin:
    image: dpage/pgadmin4:latest
   
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - go-postgres
    networks:
      - go-network
  
networks: 
  go-network:
    driver: bridge

volumes:
  pgdata: